blog_researcher_task:
  description: >
    Research the technical and conceptual aspects of {topic}. Summarize key ideas, real-world examples, technical challenges, and potential solutions in a structured format.
  expected_output: >
    A research document including:
      Definition: A concise definition of {topic}.
      Key Concepts: Explanation of core ideas or processes involved.
      Applications: Real-world use cases and examples.
      Challenges & Solutions: Technical or practical challenges and current solutions.
      References: Any notable research papers or resources (e.g., McMahan et al.'s paper for Federated Learning).
  agent: AI_Blog_Researcher

content_strategy_task:
  description: >
    Create a detailed blog outline for {topic}. Use the research material to define the structure, ensuring it resonates with the audience. Include section explanations and a logical flow.
  expected_output: >
    A structured blog outline with:
      Title: Catchy and relevant to {topic}.
      Headings/Subheadings: Organized to provide clarity and logical progression.
      Section Explanation: A brief note about each section's purpose and importance.
  agent: Content_Strategist

content_creation_task:
  description: >
    Write an engaging, insightful, and technically accurate blog post based on the provided outline for {topic}. Make the content relatable and use storytelling to simplify complex ideas.
  expected_output: >
    A fully written blog post with:
      Title & Introduction: Clearly defining the topic and its significance.
      Main Content: Detailed, section-wise explanation including examples, practical applications, and a step-by-step breakdown of processes where applicable.
      Conclusion: Summarize key points, emphasizing the broader impact of the topic.
  agent: Creative_Blogger

seo_optimization_task:
  description: >
    Optimize the blog post for search engines while preserving its narrative style. Research relevant keywords and incorporate them naturally. Format the content to improve readability and ensure it ranks well.
  expected_output: >
    A fully optimized blog post in HTML format with:
      Keywords: Integrated seamlessly into the content.
      SEO-friendly Title: Revised for search ranking.
      HTML Format:
          <div>
            <div><strong>'title'</strong></div>
            <div>
             <section>
              <h2><strong>'heading'</strong></h2>
              <p>'content'</p>
              </section>
              ...
            </div>
          </div>

  agent: SEO_Analyst
